version: "3.9"

services:
  queue:
    container_name: poc_rabbit_queue
    image: rabbitmq:3.8.11-management
    networks:
      - compose-network-dev
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root_password
    healthcheck:
      test: "rabbitmq-diagnostics -q ping"
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  db-data:
networks:
  compose-network-dev:
    driver: bridge
